services:
  - type: web
    name: rag-assistant-api
    env: python
    plan: free
    branch: knowledge_base_retriever
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health
    envVars:
      - key: PINECONE_INDEX_NAME
        value: vivasoft
      - key: VALIDATOR_URL
        value: https://provider-credential-validator.onrender.com/validate
